version: "3.9"

services:
    epsolarexporter:
        build: .
        container_name: epsolarexporter
        ports: 
            - 2112:2112
        networks: 
            - containerproxy
    
    exporterprometheus:
        image: prom/prometheus
        container_name: exporterprometheus
        ports:
            - 9091:9090
        volumes: 
            - ./prometheus:/etc/prometheus
            - ./prometheus/data:/prometheus
        networks: 
            - containerproxy

networks: 
    containerproxy:
        name: proxy